name: Check node project
on: [pull_request]
jobs:
    check_uts:
      runs-on: ubuntu-latest
      steps:
       - name: checkout the repository code
         uses: actions/checkout@v3
       - name: install node
         uses: actions/setup-node@v3
         with:
            node-version: 18
       - name: install dependencies
         run: npm install
       - name: run Tests  
         run: npm run test   